name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment when pushing to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'  # Use the latest stable Flutter version

      - name: Enable Flutter Web
        run: flutter config --enable-web

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --release

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main  # Deploy directly to the main branch of appu-devloper.github.io
          repository-name: Appu-Devloper/appu-devloper.github.io
          folder: build/web
          token: ${{ secrets.GH_PAT }}  # Use Personal Access Token
          clean: true  # Removes old files before deploying
# git commit -m "feat: Initial deployment of Flutter Web to GitHub Pages"
# git push origin main --force